using Pulse.Billing.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pulse.Billing.Entities
{
    public class Payment
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public Guid InvoiceId { get; set; }

        public decimal Amount { get; set; }

        // Current state of this payment.
        public PaymentStatus Status { get; set; }

        public PaymentMethodType Method { get; set; }
        public string Provider { get; set; } = string.Empty;  // Payment gateway used, e.g. Paystack.

        public string? ProviderReference { get; set; } // Reference generated by the payment provider. On both initiate and other states
        public DateTime CreatedAt { get; set; }
        public DateTime? CompletedAt { get; set; }
    }
}
